// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: deals.proto

package grpcapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ----------------------------------------
// The Request & Response Messages
// ----------------------------------------
type GetTrackedGamesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrackedGamesRequest) Reset() {
	*x = GetTrackedGamesRequest{}
	mi := &file_deals_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrackedGamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrackedGamesRequest) ProtoMessage() {}

func (x *GetTrackedGamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deals_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrackedGamesRequest.ProtoReflect.Descriptor instead.
func (*GetTrackedGamesRequest) Descriptor() ([]byte, []int) {
	return file_deals_proto_rawDescGZIP(), []int{0}
}

func (x *GetTrackedGamesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetTrackedGamesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 'repeated' is Protobuf's way of saying this is a List or Array
	Games         []*TrackedGame `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrackedGamesResponse) Reset() {
	*x = GetTrackedGamesResponse{}
	mi := &file_deals_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrackedGamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrackedGamesResponse) ProtoMessage() {}

func (x *GetTrackedGamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deals_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrackedGamesResponse.ProtoReflect.Descriptor instead.
func (*GetTrackedGamesResponse) Descriptor() ([]byte, []int) {
	return file_deals_proto_rawDescGZIP(), []int{1}
}

func (x *GetTrackedGamesResponse) GetGames() []*TrackedGame {
	if x != nil {
		return x.Games
	}
	return nil
}

// ----------------------------------------
// The Core Data Model
// ----------------------------------------
type TrackedGame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	TargetPrice   float64                `protobuf:"fixed64,3,opt,name=target_price,json=targetPrice,proto3" json:"target_price,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackedGame) Reset() {
	*x = TrackedGame{}
	mi := &file_deals_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackedGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackedGame) ProtoMessage() {}

func (x *TrackedGame) ProtoReflect() protoreflect.Message {
	mi := &file_deals_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackedGame.ProtoReflect.Descriptor instead.
func (*TrackedGame) Descriptor() ([]byte, []int) {
	return file_deals_proto_rawDescGZIP(), []int{2}
}

func (x *TrackedGame) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *TrackedGame) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TrackedGame) GetTargetPrice() float64 {
	if x != nil {
		return x.TargetPrice
	}
	return 0
}

func (x *TrackedGame) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

var File_deals_proto protoreflect.FileDescriptor

const file_deals_proto_rawDesc = "" +
	"\n" +
	"\vdeals.proto\x12\n" +
	"vaportrack\"1\n" +
	"\x16GetTrackedGamesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"H\n" +
	"\x17GetTrackedGamesResponse\x12-\n" +
	"\x05games\x18\x01 \x03(\v2\x17.vaportrack.TrackedGameR\x05games\"z\n" +
	"\vTrackedGame\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12!\n" +
	"\ftarget_price\x18\x03 \x01(\x01R\vtargetPrice\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive2i\n" +
	"\vGameTracker\x12Z\n" +
	"\x0fGetTrackedGames\x12\".vaportrack.GetTrackedGamesRequest\x1a#.vaportrack.GetTrackedGamesResponseBQZ6vaportrack/engine/internal/infrastructure/grpc;grpcapi\xaa\x02\x16VaporTrack.Client.Grpcb\x06proto3"

var (
	file_deals_proto_rawDescOnce sync.Once
	file_deals_proto_rawDescData []byte
)

func file_deals_proto_rawDescGZIP() []byte {
	file_deals_proto_rawDescOnce.Do(func() {
		file_deals_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_deals_proto_rawDesc), len(file_deals_proto_rawDesc)))
	})
	return file_deals_proto_rawDescData
}

var file_deals_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_deals_proto_goTypes = []any{
	(*GetTrackedGamesRequest)(nil),  // 0: vaportrack.GetTrackedGamesRequest
	(*GetTrackedGamesResponse)(nil), // 1: vaportrack.GetTrackedGamesResponse
	(*TrackedGame)(nil),             // 2: vaportrack.TrackedGame
}
var file_deals_proto_depIdxs = []int32{
	2, // 0: vaportrack.GetTrackedGamesResponse.games:type_name -> vaportrack.TrackedGame
	0, // 1: vaportrack.GameTracker.GetTrackedGames:input_type -> vaportrack.GetTrackedGamesRequest
	1, // 2: vaportrack.GameTracker.GetTrackedGames:output_type -> vaportrack.GetTrackedGamesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_deals_proto_init() }
func file_deals_proto_init() {
	if File_deals_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_deals_proto_rawDesc), len(file_deals_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_deals_proto_goTypes,
		DependencyIndexes: file_deals_proto_depIdxs,
		MessageInfos:      file_deals_proto_msgTypes,
	}.Build()
	File_deals_proto = out.File
	file_deals_proto_goTypes = nil
	file_deals_proto_depIdxs = nil
}
