// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.5
// source: deals.proto

package grpcapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameTracker_GetTrackedGames_FullMethodName = "/vaportrack.GameTracker/GetTrackedGames"
)

// GameTrackerClient is the client API for GameTracker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ----------------------------------------
// The Service Definition
// ----------------------------------------
type GameTrackerClient interface {
	GetTrackedGames(ctx context.Context, in *GetTrackedGamesRequest, opts ...grpc.CallOption) (*GetTrackedGamesResponse, error)
}

type gameTrackerClient struct {
	cc grpc.ClientConnInterface
}

func NewGameTrackerClient(cc grpc.ClientConnInterface) GameTrackerClient {
	return &gameTrackerClient{cc}
}

func (c *gameTrackerClient) GetTrackedGames(ctx context.Context, in *GetTrackedGamesRequest, opts ...grpc.CallOption) (*GetTrackedGamesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrackedGamesResponse)
	err := c.cc.Invoke(ctx, GameTracker_GetTrackedGames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameTrackerServer is the server API for GameTracker service.
// All implementations must embed UnimplementedGameTrackerServer
// for forward compatibility.
//
// ----------------------------------------
// The Service Definition
// ----------------------------------------
type GameTrackerServer interface {
	GetTrackedGames(context.Context, *GetTrackedGamesRequest) (*GetTrackedGamesResponse, error)
	mustEmbedUnimplementedGameTrackerServer()
}

// UnimplementedGameTrackerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameTrackerServer struct{}

func (UnimplementedGameTrackerServer) GetTrackedGames(context.Context, *GetTrackedGamesRequest) (*GetTrackedGamesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrackedGames not implemented")
}
func (UnimplementedGameTrackerServer) mustEmbedUnimplementedGameTrackerServer() {}
func (UnimplementedGameTrackerServer) testEmbeddedByValue()                     {}

// UnsafeGameTrackerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameTrackerServer will
// result in compilation errors.
type UnsafeGameTrackerServer interface {
	mustEmbedUnimplementedGameTrackerServer()
}

func RegisterGameTrackerServer(s grpc.ServiceRegistrar, srv GameTrackerServer) {
	// If the following call panics, it indicates UnimplementedGameTrackerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameTracker_ServiceDesc, srv)
}

func _GameTracker_GetTrackedGames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrackedGamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameTrackerServer).GetTrackedGames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameTracker_GetTrackedGames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameTrackerServer).GetTrackedGames(ctx, req.(*GetTrackedGamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GameTracker_ServiceDesc is the grpc.ServiceDesc for GameTracker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameTracker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vaportrack.GameTracker",
	HandlerType: (*GameTrackerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTrackedGames",
			Handler:    _GameTracker_GetTrackedGames_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deals.proto",
}
